### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by ccronje** [AGLDWG/TR#11]
On https://github.com/AGLDWG/TR/blob/master/guidelines/URI-Guidelines-for-publishing-linked-datasets-on-data.gov.au-v02.md under Section 7 the URL http://www.data.gov.au/dataset/location-of-act-schools seems to be broken - there is a working one at https://www.data.act.gov.au/Education/ACT-School-Locations/q8rt-q8cy

**Comment by nicholascar** [comment]
Thanks for the tip to working resource.

I'm going to close this Issue though as the Guidelines have moved on to a v2.0: <https://github.com/AGLDWG/guidelines>.
