### ISSUE TITLE
Link to ACT schools is broken (404)

### ISSUE THREAD

**Issue by F3RR3T** [AGLDWG/TR#14]
In this document:
* (https://github.com/AGLDWG/TR/blob/master/guidelines/latest.md)
there is a link to locations of ACT schools: (http://www.data.gov.au/dataset/location-of-act-schools)
That link leads to a 404.

However, I found a link which might do the job: (https://www.data.act.gov.au/Education/ACT-School-Locations-2017-archived/q8rt-q8cy)

**Comment by nicholascar** [comment]
Thanks very much for that Stephen! I've fixed the link as you suggest.
